# Generated by Django 6.0.3 on 2026-04-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('players', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sports/')),
            ],
        ),
    ]
